/**
 * Majority Judgment API
 * This is a **deliberation service** using **majority judgment** polling. It's **libre software** ([source](https://github.com/mieuxvoter)) made and maintained by [MieuxVoter.fr](https://mieuxvoter.fr). You're browsing the API documentation and sandbox.  ## Use one of the known clients  - TODO: add an URL to a client of the API   ## Try it out the hard way  ### Create an account  You will need a user account to interact with polls. Head to **Registration** → `POST /users` below. Click _Try it out_, set your desired credentials, and execute the query. Scroll down to see the response.  ### Authenticate  Use your credentials in the **Login** → `POST /_jwt`, and the API will return a Json Web Token valid for one hour. Copy the token (not the whole response, and without quotes) in the field behind the `Authorize 🔒` button.  ### Create a poll  **Poll** → `POST /polls`  Keep the response, you'll need the uuids.  > TODO: document invitation generation  ### Submit judgments  **Ballot** → `POST /polls/{pollId}/proposals/{proposalId}/ballots`  One request per proposal, for now.  We plan on making an endpoint to submit them all at once.  ### Collect the results  **Result** → `GET /polls/{id}/result`  ## Use a generated client library  - for php  (link!) - for typescript-node  (link!!) - …  There are clients we can generate for most languages. Get in touch if you'd like one in particular! Or clone this project and use `bin/generate-client.bash -t whatever`. 
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse200HydraSearchHydraMapping from './InlineResponse200HydraSearchHydraMapping';

/**
 * The InlineResponse200HydraSearch model module.
 * @module MieuxVoter/model/InlineResponse200HydraSearch
 * @version 0.0.0-dev
 */
class InlineResponse200HydraSearch {
    /**
     * Constructs a new <code>InlineResponse200HydraSearch</code>.
     * @alias module:MieuxVoter/model/InlineResponse200HydraSearch
     */
    constructor() { 
        
        InlineResponse200HydraSearch.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200HydraSearch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:MieuxVoter/model/InlineResponse200HydraSearch} obj Optional instance to populate.
     * @return {module:MieuxVoter/model/InlineResponse200HydraSearch} The populated <code>InlineResponse200HydraSearch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200HydraSearch();

            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('hydra:template')) {
                obj['hydra:template'] = ApiClient.convertToType(data['hydra:template'], 'String');
            }
            if (data.hasOwnProperty('hydra:variableRepresentation')) {
                obj['hydra:variableRepresentation'] = ApiClient.convertToType(data['hydra:variableRepresentation'], 'String');
            }
            if (data.hasOwnProperty('hydra:mapping')) {
                obj['hydra:mapping'] = ApiClient.convertToType(data['hydra:mapping'], [InlineResponse200HydraSearchHydraMapping]);
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getType() {
        return this.@type;
    }

    /**
     * @param {String} type
     */
    setType(type) {
        this['@type'] = type;
    }
/**
     * @return {String}
     */
    getHydratemplate() {
        return this.hydra:template;
    }

    /**
     * @param {String} hydratemplate
     */
    setHydratemplate(hydratemplate) {
        this['hydra:template'] = hydratemplate;
    }
/**
     * @return {String}
     */
    getHydravariableRepresentation() {
        return this.hydra:variableRepresentation;
    }

    /**
     * @param {String} hydravariableRepresentation
     */
    setHydravariableRepresentation(hydravariableRepresentation) {
        this['hydra:variableRepresentation'] = hydravariableRepresentation;
    }
/**
     * @return {Array.<module:MieuxVoter/model/InlineResponse200HydraSearchHydraMapping>}
     */
    getHydramapping() {
        return this.hydra:mapping;
    }

    /**
     * @param {Array.<module:MieuxVoter/model/InlineResponse200HydraSearchHydraMapping>} hydramapping
     */
    setHydramapping(hydramapping) {
        this['hydra:mapping'] = hydramapping;
    }

}

/**
 * @member {String} @type
 */
InlineResponse200HydraSearch.prototype['@type'] = undefined;

/**
 * @member {String} hydra:template
 */
InlineResponse200HydraSearch.prototype['hydra:template'] = undefined;

/**
 * @member {String} hydra:variableRepresentation
 */
InlineResponse200HydraSearch.prototype['hydra:variableRepresentation'] = undefined;

/**
 * @member {Array.<module:MieuxVoter/model/InlineResponse200HydraSearchHydraMapping>} hydra:mapping
 */
InlineResponse200HydraSearch.prototype['hydra:mapping'] = undefined;






export default InlineResponse200HydraSearch;

