/**
 * Majority Judgment API
 * This is a **deliberation service** using **majority judgment** polling. It's **libre software** ([source](https://github.com/mieuxvoter)) made and maintained by [MieuxVoter.fr](https://mieuxvoter.fr). You're browsing the API documentation and sandbox.  ## Use one of the known clients  - TODO: add an URL to a client of the API   ## Try it out the hard way  ### Create an account  You will need a user account to interact with polls. Head to **Registration** → `POST /users` below. Click _Try it out_, set your desired credentials, and execute the query. Scroll down to see the response.  ### Authenticate  Use your credentials in the **Login** → `POST /_jwt`, and the API will return a Json Web Token valid for one hour. Copy the token (not the whole response, and without quotes) in the field behind the `Authorize 🔒` button.  ### Create a poll  **Poll** → `POST /polls`  Keep the response, you'll need the uuids.  > TODO: document invitation generation  ### Submit judgments  **Ballot** → `POST /polls/{pollId}/proposals/{proposalId}/ballots`  One request per proposal, for now.  We plan on making an endpoint to submit them all at once.  ### Collect the results  **Result** → `GET /polls/{id}/result`  ## Use a generated client library  - for php  (link!) - for typescript-node  (link!!) - …  There are clients we can generate for most languages. Get in touch if you'd like one in particular! Or clone this project and use `bin/generate-client.bash -t whatever`. 
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProposalGradeResultRead model module.
 * @module MieuxVoter/model/ProposalGradeResultRead
 * @version 0.0.0-dev
 */
class ProposalGradeResultRead {
    /**
     * Constructs a new <code>ProposalGradeResultRead</code>.
     * Results for one Grade of one Proposal, basically the tally of Ballots for this Grade and Proposal, but there might be more information in there in the future.
     * @alias module:MieuxVoter/model/ProposalGradeResultRead
     */
    constructor() { 
        
        ProposalGradeResultRead.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProposalGradeResultRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:MieuxVoter/model/ProposalGradeResultRead} obj Optional instance to populate.
     * @return {module:MieuxVoter/model/ProposalGradeResultRead} The populated <code>ProposalGradeResultRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProposalGradeResultRead();

            if (data.hasOwnProperty('grade')) {
                obj['grade'] = ApiClient.convertToType(data['grade'], 'String');
            }
            if (data.hasOwnProperty('proposal')) {
                obj['proposal'] = ApiClient.convertToType(data['proposal'], 'String');
            }
            if (data.hasOwnProperty('tally')) {
                obj['tally'] = ApiClient.convertToType(data['tally'], 'Number');
            }
        }
        return obj;
    }

/**
     * Returns The IRI of the Grade this Result is about.
     * @return {String}
     */
    getGrade() {
        return this.grade;
    }

    /**
     * Sets The IRI of the Grade this Result is about.
     * @param {String} grade The IRI of the Grade this Result is about.
     */
    setGrade(grade) {
        this['grade'] = grade;
    }
/**
     * Returns The IRI of the Proposal this Result is about.
     * @return {String}
     */
    getProposal() {
        return this.proposal;
    }

    /**
     * Sets The IRI of the Proposal this Result is about.
     * @param {String} proposal The IRI of the Proposal this Result is about.
     */
    setProposal(proposal) {
        this['proposal'] = proposal;
    }
/**
     * Returns Amount of Ballots emitted for this Grade on the Proposal.
     * @return {Number}
     */
    getTally() {
        return this.tally;
    }

    /**
     * Sets Amount of Ballots emitted for this Grade on the Proposal.
     * @param {Number} tally Amount of Ballots emitted for this Grade on the Proposal.
     */
    setTally(tally) {
        this['tally'] = tally;
    }

}

/**
 * The IRI of the Grade this Result is about.
 * @member {String} grade
 */
ProposalGradeResultRead.prototype['grade'] = undefined;

/**
 * The IRI of the Proposal this Result is about.
 * @member {String} proposal
 */
ProposalGradeResultRead.prototype['proposal'] = undefined;

/**
 * Amount of Ballots emitted for this Grade on the Proposal.
 * @member {Number} tally
 */
ProposalGradeResultRead.prototype['tally'] = undefined;






export default ProposalGradeResultRead;

