/**
 * Majority Judgment API
 * This is a **deliberation service** using **majority judgment** polling. It's **libre software** ([source](https://github.com/mieuxvoter)) made and maintained by [MieuxVoter.fr](https://mieuxvoter.fr). You're browsing the API documentation and sandbox.  ## Use one of the known clients  - TODO: add an URL to a client of the API   ## Try it out the hard way  ### Create an account  You will need a user account to interact with polls. Head to **Registration** → `POST /users` below. Click _Try it out_, set your desired credentials, and execute the query. Scroll down to see the response.  ### Authenticate  Use your credentials in the **Login** → `POST /_jwt`, and the API will return a Json Web Token valid for one hour. Copy the token (not the whole response, and without quotes) in the field behind the `Authorize 🔒` button.  ### Create a poll  **Poll** → `POST /polls`  Keep the response, you'll need the uuids.  > TODO: document invitation generation  ### Submit judgments  **Ballot** → `POST /polls/{pollId}/proposals/{proposalId}/ballots`  One request per proposal, for now.  We plan on making an endpoint to submit them all at once.  ### Collect the results  **Result** → `GET /polls/{id}/result`  ## Use a generated client library  - for php  (link!) - for typescript-node  (link!!) - …  There are clients we can generate for most languages. Get in touch if you'd like one in particular! Or clone this project and use `bin/generate-client.bash -t whatever`. 
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProposalGradeResultjsonldRead model module.
 * @module MieuxVoter/model/ProposalGradeResultjsonldRead
 * @version 0.0.0-dev
 */
class ProposalGradeResultjsonldRead {
    /**
     * Constructs a new <code>ProposalGradeResultjsonldRead</code>.
     * Results for one Grade of one Proposal, basically the tally of Ballots for this Grade and Proposal, but there might be more information in there in the future.
     * @alias module:MieuxVoter/model/ProposalGradeResultjsonldRead
     */
    constructor() { 
        
        ProposalGradeResultjsonldRead.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProposalGradeResultjsonldRead</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:MieuxVoter/model/ProposalGradeResultjsonldRead} obj Optional instance to populate.
     * @return {module:MieuxVoter/model/ProposalGradeResultjsonldRead} The populated <code>ProposalGradeResultjsonldRead</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProposalGradeResultjsonldRead();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('grade')) {
                obj['grade'] = ApiClient.convertToType(data['grade'], 'String');
            }
            if (data.hasOwnProperty('proposal')) {
                obj['proposal'] = ApiClient.convertToType(data['proposal'], 'String');
            }
            if (data.hasOwnProperty('tally')) {
                obj['tally'] = ApiClient.convertToType(data['tally'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} @context
 */
ProposalGradeResultjsonldRead.prototype['@context'] = undefined;

/**
 * @member {String} @id
 */
ProposalGradeResultjsonldRead.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
ProposalGradeResultjsonldRead.prototype['@type'] = undefined;

/**
 * The IRI of the Grade this Result is about.
 * @member {String} grade
 */
ProposalGradeResultjsonldRead.prototype['grade'] = undefined;

/**
 * The IRI of the Proposal this Result is about.
 * @member {String} proposal
 */
ProposalGradeResultjsonldRead.prototype['proposal'] = undefined;

/**
 * Amount of Ballots emitted for this Grade on the Proposal.
 * @member {Number} tally
 */
ProposalGradeResultjsonldRead.prototype['tally'] = undefined;






export default ProposalGradeResultjsonldRead;

