/**
 * Majority Judgment API
 * This is a **deliberation service** using **majority judgment** polling. It's **libre software** ([source](https://github.com/mieuxvoter)) made and maintained by [MieuxVoter.fr](https://mieuxvoter.fr). You're browsing the API documentation and sandbox.  ## Use one of the known clients  - TODO: add an URL to a client of the API   ## Try it out the hard way  ### Create an account  You will need a user account to interact with polls. Head to **Registration** → `POST /users` below. Click _Try it out_, set your desired credentials, and execute the query. Scroll down to see the response.  ### Authenticate  Use your credentials in the **Login** → `POST /_jwt`, and the API will return a Json Web Token valid for one hour. Copy the token (not the whole response, and without quotes) in the field behind the `Authorize 🔒` button.  ### Create a poll  **Poll** → `POST /polls`  Keep the response, you'll need the uuids.  > TODO: document invitation generation  ### Submit judgments  **Ballot** → `POST /polls/{pollId}/proposals/{proposalId}/ballots`  One request per proposal, for now.  We plan on making an endpoint to submit them all at once.  ### Collect the results  **Result** → `GET /polls/{id}/result`  ## Use a generated client library  - for php  (link!) - for typescript-node  (link!!) - …  There are clients we can generate for most languages. Get in touch if you'd like one in particular! Or clone this project and use `bin/generate-client.bash -t whatever`. 
 *
 * The version of the OpenAPI document: 0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserjsonldEdit model module.
 * @module MieuxVoter/model/UserjsonldEdit
 * @version 0.0.0-dev
 */
class UserjsonldEdit {
    /**
     * Constructs a new <code>UserjsonldEdit</code>.
     * Users create, maintain and participate in Polls.
     * @alias module:MieuxVoter/model/UserjsonldEdit
     * @param username {String} The username must be unique amongst Users.
     */
    constructor(username) { 
        
        UserjsonldEdit.initialize(this, username);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username) { 
        obj['username'] = username;
    }

    /**
     * Constructs a <code>UserjsonldEdit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:MieuxVoter/model/UserjsonldEdit} obj Optional instance to populate.
     * @return {module:MieuxVoter/model/UserjsonldEdit} The populated <code>UserjsonldEdit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserjsonldEdit();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getContext() {
        return this.@context;
    }

    /**
     * @param {String} context
     */
    setContext(context) {
        this['@context'] = context;
    }
/**
     * @return {String}
     */
    getId() {
        return this.@id;
    }

    /**
     * @param {String} id
     */
    setId(id) {
        this['@id'] = id;
    }
/**
     * @return {String}
     */
    getType() {
        return this.@type;
    }

    /**
     * @param {String} type
     */
    setType(type) {
        this['@type'] = type;
    }
/**
     * Returns When provided, the email must be unique amongst Users.
     * @return {String}
     */
    getEmail() {
        return this.email;
    }

    /**
     * Sets When provided, the email must be unique amongst Users.
     * @param {String} email When provided, the email must be unique amongst Users.
     */
    setEmail(email) {
        this['email'] = email;
    }
/**
     * Returns The username must be unique amongst Users.
     * @return {String}
     */
    getUsername() {
        return this.username;
    }

    /**
     * Sets The username must be unique amongst Users.
     * @param {String} username The username must be unique amongst Users.
     */
    setUsername(username) {
        this['username'] = username;
    }
/**
     * Returns The plain password of the User.
     * @return {String}
     */
    getPassword() {
        return this.password;
    }

    /**
     * Sets The plain password of the User.
     * @param {String} password The plain password of the User.
     */
    setPassword(password) {
        this['password'] = password;
    }

}

/**
 * @member {String} @context
 */
UserjsonldEdit.prototype['@context'] = undefined;

/**
 * @member {String} @id
 */
UserjsonldEdit.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
UserjsonldEdit.prototype['@type'] = undefined;

/**
 * When provided, the email must be unique amongst Users.
 * @member {String} email
 */
UserjsonldEdit.prototype['email'] = undefined;

/**
 * The username must be unique amongst Users.
 * @member {String} username
 */
UserjsonldEdit.prototype['username'] = undefined;

/**
 * The plain password of the User.
 * @member {String} password
 */
UserjsonldEdit.prototype['password'] = undefined;






export default UserjsonldEdit;

